channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - nodejs=16.14.2
  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework-browser==12.4.0
      - rpaframework[aws]==14.1.1 # https://rpaframework.org/releasenotes.html
      - pymsteams==0.2.1

rccPostInstall:
  - rfbrowser init